### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for GPTActor:

### ISSUE THREAD

**Issue by oldwangggggg** [Mowenyii/PAE#2]
RuntimeError: Error(s) in loading state_dict for GPTActor:
        Missing key(s) in state_dict: "transformer.position_embedding_layer.weight". 
        Unexpected key(s) in state_dict: "transformer.postion_embedding_layer.weight". 
        

Error in :
  gpt_sft = torch.compile(GPTActor.from_checkpoint(
          cfg,
          sft)).to(device) 
        
and : 

       checkpoint = torch.load(ckpt_path, map_location="cpu")
        
        model.load_state_dict(checkpoint["model_state_dict"], strict=True)

**Comment by oldwangggggg** [comment]
**SOLUSION:**
_**The code was wrong, because:**_
              This error is due to a mismatch in key names within the `state_dict`.
              
              Specifically, the error message indicates:
              
              - The key `transformer.position_embedding_layer.weight` is missing.
              - The unexpected key `transformer.postion_embedding_layer.weight` is present.
              
              From the error message, it is clear that the key `postion` is misspelled and should be `position`. This causes the  `load_state_dict` method to fail in correctly matching the parameters in the model.

_We back to the code in PAE-main/src/gpt.py , in Line 721 , change Line 721 and 722 to:_

           checkpoint = torch.load(ckpt_path, map_location="cpu")
            state_dict = checkpoint["model_state_dict"]
            state_dict["transformer.position_embedding_layer.weight"] = state_dict.pop("transformer.postion_embedding_layer.weight")
            model.load_state_dict(state_dict, strict=False)

**Comment by Mowenyii** [comment]
Hi. May I ask which command you were running when you encountered this error?

**Comment by oldwangggggg** [comment]
> Hi. May I ask which command you were running when you encountered this error?
**It's:**
  python demo_DF_prompt.py

**Comment by Mowenyii** [comment]
Thank you for pointing out the issue. The correct code version is commit 3a744f2. I will fix this bug as soon as possible.

**Comment by Mowenyii** [comment]
Thank you for pointing out the bug. The correct code version is commit https://github.com/Mowenyii/PAE/commit/e440c5433f36980c864da1c06413bebc4ff3bcbb.
